server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user_service
              uri: http://localhost:8081
              predicates:
                - Path=/user-service/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Request-Source,Gateway
            - id: notification_service
              uri: http://localhost:8082
              predicates:
                - Path=/notification-service/**
              filters:
                - StripPrefix=1